# fly.toml app configuration file generated for basketball-stats-webapp on 2024-11-03T22:00:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'basketball-stats-webapp'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
